apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers: 
        - name: tasks
          image: sebastr/kub-demo-tasks:latest
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default.svc.cluster.local"
            - name: TASKS_FOLDER
              value: "tasks"
        